<a href="https://colab.research.google.com/github/93san/angularJS-practice/blob/main/loan_predict.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df=pd.read_csv("/content/loan.csv")
df.head()

,age,gender,occupation,education_level,marital_status,income,credit_score,loan_status
0,32,Male,Engineer,Bachelor's,Married,85000,720,Approved
1,45,Female,Teacher,Master's,Single,62000,680,Approved
2,28,Male,Student,High School,Single,25000,590,Denied
3,51,Female,Manager,Bachelor's,Married,105000,780,Approved
4,36,Male,Accountant,Bachelor's,Married,75000,710,Approved

In [10]:
from sklearn.model_selection import train_test_split
null_values_total = df.isnull().sum()
print(null_values_total)

x=df.drop('loan_status',axis=1)
x = pd.get_dummies(x)
y=df['loan_status']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

age                0
gender             0
occupation         0
education_level    0
marital_status     0
income             0
credit_score       0
loan_status        0
dtype: int64

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
logisticRegr = LogisticRegression()
logisticRegr.fit(X_train, y_train)
y_pred = logisticRegr.predict(X_test)
print(y_pred)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

['Approved' 'Denied' 'Approved' 'Approved' 'Approved' 'Approved' 'Denied'
 'Denied' 'Denied' 'Approved' 'Approved' 'Approved' 'Approved']
Accuracy: 1.0

Classification Report:
              precision    recall  f1-score   support

    Approved       1.00      1.00      1.00         9
      Denied       1.00      1.00      1.00         4

    accuracy                           1.00        13
   macro avg       1.00      1.00      1.00        13
weighted avg       1.00      1.00      1.00        13